#.travis.yml

language: node_js
node_js:
  - "8.1.3"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - npm install -g firebase-tools
  - npm install -g preact-cli
  - npm install

script:
  - preact build
  - cd functions
  - npm install
  - cd ..

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
